caxlsx/caxlsx

axlsx.gemspec
nokogiri <1.10.4 and rubyzip < 1.2.3 had CVEs and/or regressions, and Ruby 2.4.7 is the minimum maintenance level.
=> Bump dependencies for nokogiri, ruby, and rubyzip.

lib/axlsx/stylesheet/font.rb, test/stylesheet/tc_font.rb, test/stylesheet/tc_styles.rb
This PR tries to fix Issue https://github.com/caxlsx/caxlsx/issues/14
Solution: 
- The correct supported values for underline are `:none, :single, :double, :singleAccounting, :doubleAccounting`
- Allow and Set the correct value from the above list.
- Also try to maintain backward compatibility.
=> Fix validate document error with font option underline

lib/axlsx/util/validators.rb
Fixnum is removed by 12d6433, but this typo was remained.
=> Remove a typo from comment

examples/example.rb, lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/row.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/workbook/worksheet/tc_cell.rb, test/workbook/worksheet/tc_row.rb
Added the option to pass in escape_formulas: true into the #add_row method.
In John Legrand's words, from this issue #624
"""
It would be nice to be able to pass an option to block formula injection. We use this Gem to let clients export tables to excel sheets. This is an unsafe practice because a formula could be injected. There should be an ability to block these injections to OWASP standards. (prepending "'" to anything that starts with something possibly malicious. https://www.owasp.org/index.php/CSV_Injection
"""
=> Add option to protect against csv injection attacks

lib/axlsx/drawing/series_title.rb, lib/axlsx/drawing/title.rb, test/drawing/tc_series_title.rb, test/drawing/tc_title.rb, test/tc_axlsx.rb
I'm making this PR to fix #37. 
There's an old test that required some changes: test/tc_axlsx.rb set the `Axlsx.trust_input` value to true which lead to ignore the CGI escapes.
All the other (new) tests are checking if the generated XMLs are valid or not with xml-specific special characters in the given title or cell.
=> Escape characters in charts

examples/colored_links.rb
I tidied up the example mentioned in #32 to match most of the current guides of rubocop. It resolves the given issue, however the example directory remains a mess.
There are a lot of snippets in the `examples/example.rb` (in a hardly readable format). Some of the examples are in separate files (I guess it was easier to create a new file than follow the pattern in the examples.rb). The comments around the snippets not always tell you what it really does, etc.
I'm suggesting that we should move the examples from the repository to the github wiki with better categorization and more unified format (e.g.: call the package `p` and workbook `wb`, etc).
I'm making a demo of what I imagined and link it here in the PR soon
=> Remove global variables from example #32

lib/axlsx/workbook/worksheet/col.rb, test/workbook/worksheet/tc_col.rb
Maximum column width limit in MS Excel is 255 characters https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
If this value is exceeded, MS Excel gets stuck and doesn't allow column resizing.
Ported from https://github.com/randym/axlsx/pull/653
=> Set column width to the maximum allowed value

lib/axlsx/util/constants.rb, lib/axlsx/workbook/worksheet/cell.rb, test/workbook/worksheet/tc_cell.rb
Prior to this change, strings like "1e12345" would be interpreted as float values, regardless of the actual value of the exponent (which easily could be out of range for Ruby).
In case the exponent was greater than `Float::MAX_10_EXP` (usually 308), this would result in a cell of type `:float` containing the literal string `"Infinity"`. Excel can not parse such cells and therefore gives a “corrupt data” error.
In case the exponent was less than `Float::MIN_10_EXP` (usually -307) the cell would contain `0.0`. This does not result in Excel throwing an error, but probably isn't the expected result either.
Note that this problem is quite likely to happen when creating a worksheet with hexadecimal strings, because e.g. "1234e567" is a perfectly valid hex value.
The additional range check of …
=> Fix type detection for floats with out-of-rage exponents

CHANGELOG.md, lib/axlsx.rb, lib/axlsx/package.rb, lib/axlsx/util/zip_command.rb, test/tc_package.rb
Add a `:zip_command` option to `Axlsx::Package#serialize` that allows
the user to specify an alternate command to use to perform the zip
operation on the XLSX file contents.
The default zip operation is provided by RubyZip. On large documents
users may experience faster zip times using a zip binary.
Resolves #55
=> Add option to `#serialize` with system zip command

.travis.yml
I thought that we should keep our CI up-to-date, so
- added ruby 2.7.1
- moved every minor version to its latest patch
=> Update Ruby versions on Travis

lib/axlsx/workbook/worksheet/cell.rb, test/workbook/worksheet/tc_cell.rb
Ran into an issue today - `caxlsx` was trying to call `to_i` on an object that does not respond to it, an ActiveRecord instance.
Turns out, the `to_s` of that particular instance was returning a string consisting of only numericals.
This change ensures that only objects that respond to `to_i` / `to_f` methods used in `cast_value` can be autodetected to `:integer` / `:float` values by `cell_type_from_value`, based on the string representation.
Should not break existing use cases, since this would have previously ended in an exception. Well, at least use cases that did not rely on formatting crashing out :D
=> Extend cell_type_from_value with sanity checks

.travis.yml, Gemfile, axlsx.gemspec
Tested with `3.0.0-preview1` and all tests are green:
```
Loaded suite /Users/walski/.rubies/ruby-3.0.0-preview1/lib/ruby/gems/3.0.0/gems/rake-13.0.1/lib/rake/rake_test_loader
Started
................................................................................................................................................................................
................................................................................................................................................................................
................................................................................................................................................................................
..................................................................................... …
```
=> Relaxes Ruby dependency to work with Ruby 3

CHANGELOG.md, lib/axlsx/workbook/worksheet/worksheet.rb, test/workbook/worksheet/tc_worksheet.rb
Closes https://github.com/caxlsx/caxlsx/issues/67
=> Fix worksheet title length enforcement

lib/axlsx/util/validators.rb, lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/data_validation.rb, test/util/tc_validators.rb, test/workbook/worksheet/tc_cell.rb
`date` type is valid cell type, but is missing in validator. It's impossible to set it explicitly.
Fixes https://github.com/caxlsx/caxlsx/issues/26
If this can be tested somehow, please let me know, not sure what test to add for this small change
=> Allow to set cell type to `date`

lib/axlsx/workbook/worksheet/pivot_table_cache_definition.rb, test/workbook/worksheet/tc_pivot_table_cache_definition.rb
Previous to this PR, special characters in pivot table headers would generate invalid XML due to the use of the cell.value instead of cell.clean_value in pivot table cache definition serialization.
This PR adds a test and fix for this.
Before the fix, the new test failed with:
```
Failure: test_to_xml_string_for_special_characters(TestPivotTableCacheDefinition):
invalid xml: 1:382: FATAL: xmlParseEntityRef: no name, 1:383: FATAL: Unescaped '<' not allowed in attributes values, 1:383: FATAL: attributes construct error, 1:383: FATAL: Couldn't find end of Start Tag cacheField line 1, 1:384: FATAL: StartTag: invalid element name, 1:461: FATAL: Opening and ending tag mismatch: cacheFields line 1 and cacheField, 1:730: FATAL: Opening and ending tag mismatch: pivotCacheDefinition line 1 and …
```
=> Fix special characters in pivot table cache definition

lib/axlsx/workbook/worksheet/table.rb, test/workbook/worksheet/tc_table.rb
Previous to this PR, special characters in table headers would generate invalid XML due to the use of the `cell.value` instead of `cell.clean_value` in table serialization.
This PR adds a test and fix for this.
Before the fix, the new test failed with:
```
1:0: ERROR: Element '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}tableColumns': Character content other than whitespace is not allowed because the content type is 'element-only'.
F
===============================================================================
Failure: test_to_xml_string_for_special_characters(TestTable):
error free validation.
<false> is not true.
/home/rfdonnelly/repos/caxlsx/test/workbook/worksheet/tc_table.rb:80:in `test_to_xml_string_for_special_characters'
77:       errors.push error
78:       puts …
```
=> Fix special characters in table header

lib/axlsx/package.rb, test/tc_package.rb
Update `Axlsx::Package#serialize` to accept the second argument as a
boolean (being deprecated) or an options hash.
In order to transition toward using keyword arguments for
`Axlsx::Package#serialize`, change the documented method signature to an
options hash, while still parsing the second argument as `confirm_valid`
if a boolean is provided (in which case we also warn the user that a
boolean argument is deprecated).
=> Deprecate using `#serialize` with boolean argument

.travis.yml
This PR ~~updates~~ **adds** JRuby **9.2.15.0** to the CI matrix.
[JRuby 9.2.15.0 release blog post](https://www.jruby.org/2021/02/24/jruby-9-2-15-0.html)
=> CI: Add JRuby 9.2.15.0 (latest release)

.travis.yml
This PR updates the CI matrix to use latest JRuby, **9.2.16.0**.
[JRuby 9.2.16.0 release blog post](https://www.jruby.org/2021/03/03/jruby-9-2-16-0.html)
=> CI: Use jruby-9.2.16.0

axlsx.gemspec, lib/axlsx.rb, lib/axlsx/util/mime_type_utils.rb, test/tc_helper.rb, test/tc_package.rb
Mimemagic requires users to download or install additional files.
Rails used Marcel as an abstration layer on this library. Marcel
was updated to another file matching database. Following Rails in
this matter will remove the need for users to do additional work,
just to use caxlsx.
Fixes #92
=> Replace mimemagic with marcel

CHANGELOG.md, lib/axlsx/drawing/bar_3D_chart.rb, lib/axlsx/drawing/bar_chart.rb, test/drawing/tc_bar_3D_chart.rb, test/drawing/tc_bar_chart.rb
While I was working on #107 , I found that we have a `gap_width` option for `BarChart`s, however the validator seems to be off.
Given I have this code, and I need to figure out what should be instead of `something`
```ruby
require 'axlsx'
p = Axlsx::Package.new
wb = p.workbook
wb.add_worksheet(name: 'Bar Chart') do |sheet|
sheet.add_row ['A Simple Bar Chart', 'X', 'Y']
sheet.add_row ['A', 3, 4]
sheet.add_row ['B', 10, 6]
sheet.add_row ['C', 7, 2]
sheet.add_chart(Axlsx::BarChart, start_at: 'A6', end_at: 'F20') do |chart|
chart.add_series data: sheet['B2:B4'], labels: sheet['A2:A4'], title: sheet['B1']
chart.add_series data: sheet['C2:C4'], labels: sheet['A2:A4'], title: sheet['C1']
chart.bar_dir = :col
chart.gap_width = 10
chart.gap_width = something # <<- this is the problematic line …
```
=> Fix gap width validator for bar charts

lib/axlsx/package.rb, test/tc_package.rb
Addresses issues as described in https://github.com/rubyzip/rubyzip/issues/438 where the default encoding is UTF-8 but the actual zipped/deflated contents are not necessarily valid UTF-8.
As a minimal example:
```ruby
require 'axlsx.rb'
p = Axlsx::Package.new
p.workbook.add_worksheet(name: 'Test Sheet') do |ws|
ws.add_row(['A Title', 'Another Title', 'A Third Title'])
ws.add_row(['Value', 1.0, nil])
end
puts p.to_stream.string.valid_encoding?
```
=> Return output stream in binmode

CHANGELOG.md, lib/axlsx/workbook/worksheet/pivot_table.rb, test/workbook/worksheet/tc_pivot_table.rb
=> Fix invalid xml when pivot table created with more than one column in data field

README.md
Currently the link to known bugs, results in a list of 3 closed issues and no open issues. I think this link doesnt serve its purpose correctly.
=> Remove Known Bugs Section in Readme

CHANGELOG.md, lib/axlsx.rb, lib/axlsx/util/constants.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/workbook/worksheet/tc_worksheet.rb
Improve error messages when incorrect ranges are provided to `Worksheet#[]`
- Related to https://github.com/axlsx-styler-gem/axlsx_styler/issues/33 and the other referenced axlsx issues
=> Improve error for invalid ranges

lib/axlsx.rb, lib/axlsx/content_type/abstract_content_type.rb, lib/axlsx/doc_props/app.rb, lib/axlsx/drawing/d_lbls.rb, lib/axlsx/drawing/view_3D.rb, lib/axlsx/rels/relationship.rb, lib/axlsx/stylesheet/font.rb, lib/axlsx/stylesheet/styles.rb, lib/axlsx/util/serialized_attributes.rb, lib/axlsx/workbook/worksheet/cell_serializer.rb, lib/axlsx/workbook/worksheet/data_validation.rb, lib/axlsx/workbook/worksheet/rich_text_run.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/drawing/tc_chart.rb, test/drawing/tc_d_lbls.rb, test/drawing/tc_picture_locking.rb, test/stylesheet/tc_styles.rb, test/tc_axlsx.rb, test/tc_package.rb, test/workbook/worksheet/tc_worksheet_hyperlink.rb
the `axlsx` gem currently borrows a monkeypatch from ActiveSupport by adding the `instance_values` on Object. While this is convenient, it mutates Object for any ruby that loads this gem. 
I'm proposing we keep the `instance_values` functionality but move it to be isolated under the `Axlsx` constant to not pollute core ruby for any users of this Gem. 
This additionally (although I have not validated fully) will improve performance as there were several cases where `instance_values` was called inside a loop generating many hashes. 
Happy to come up with alternatives!
=> Remove Object#instance_values monkey patch

axlsx.gemspec
This PR updates gemspec file to recent styles. Here are the details:
- `date` should not be set
- RubyGems says not to set the value to [`date`](https://github.com/rubygems/rubygems/blob/fe96fb6e2ac5a8b6df5e852470d11fa854301eca/lib/rubygems/specification.rb#L1677-L1682).
- Remove deprecated `test_files` to shrink gem size
- Please see the following for details.
-  rubygems/guides#90
- rubygems/bundler#3207
=> Update gemspec to recent styles

lib/axlsx/package.rb, test/tc_package.rb
Hi. Thanks for maintaining this great gem.
Fixes #130 
According to [these lines](https://github.com/file/file/blob/ec41083645689a787cdd00cb3b5bf578aa79e46c/magic/Magdir/msooxml#L28-L38), `file` checks the **third** entry to detect the MIME type. 
> make sure the first file is correct
> skip to the second local file header
> since some documents include a 520-byte extra field following the file
> header, we need to scan for the next header
> now skip to the *third* local file header; again, we need to scan due to a
> 520-byte extra field following the file header
> and check the subdirectory name to determine which type of OOXML
`caxlsx` currently generates archive entries with wrong order: the third entry is `docProps/app.xml`.
```
$ zipinfo caxlsx.xlsx
Archive:  caxlsx.xlsx
Zip file …
```
=> Sort archive entries for correct MIME detection with `file` command

CHANGELOG.md, lib/axlsx/drawing/chart.rb, lib/axlsx/drawing/title.rb, test/drawing/tc_chart.rb, test/drawing/tc_title.rb
Before this change, a chart with a empty title would show up in Excel with a default title like “Chart title” or “Diagrammtitel”.
It was not possible to completely hide a chart title: Setting it for example to a string consisting of a single space would override Excel’s default, but the empty title did still occupy vertical space.
Per OOXML standard the `title` element is optional, so omitting it if the title is blank looks like the right thing to do and seems to work correctly in Excel:
A note about __`autoTitleDeleted`__: The standard says _“This element specifies the title shall not be shown for this chart.”_ – and so I first tried to fix this issue by changing `Chart#to_xml_string` to render this element as `true` if the title is blank (right now the element is always `false` because …
=> Fix empty chart title

lib/axlsx/drawing/chart.rb, test/drawing/tc_chart.rb
Until now this setting was hardcoded to `true`.
The setting affects whether data from hidden cells (cells with zero height or width) is used when plotting the chart.
Should be a straight forward change.
=> Implement “plot visible only” setting for charts

lib/axlsx/drawing/chart.rb, test/drawing/tc_chart.rb
Until now this setting was not present in the generated XML. According to the ECMA spec the setting defaults to true, so charts always had rounded corners.
Now rounded corners can be disabled explicitly.
Before:
After (with `rounded_corners: false`):
=> Implement “rounded corners” setting for charts

lib/axlsx/util/constants.rb, lib/axlsx/workbook/worksheet/worksheet.rb
Moves forbidden chars to a constant for easier usage in external helpers (e.g: name sanitization)
=> Move worksheet name forbidden chars to a constant

CHANGELOG.md, lib/axlsx/workbook/worksheet/pivot_table.rb, test/workbook/worksheet/tc_pivot_table.rb
Excel will crash unless both `colFields` and `colItems` are declared in the PivotTable xml.
First `field` of `colFields` needs to be set to -2 to tell Excel that the value columns comes from individual columns (data) and not groups (columns).
I do not know why `colItems` are needed, but when set, the Excel document opens without crashing.
Related to:
https://github.com/caxlsx/caxlsx/issues/110
=> Prevent Excel from crashing when multiple data columns added to PivotTable

CHANGELOG.md, examples/add_border_example.md, lib/axlsx/stylesheet/styles.rb, lib/axlsx/workbook/worksheet/border_creator.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/workbook/worksheet/tc_border_creator.rb, test/workbook/worksheet/tc_worksheet.rb
- Fix bug when calling `worksheet.add_border("A1:B2", nil)`
```
NameError: uninitialized constant Axlsx::Border::Edges
Did you mean?  Axlsx::Border::EDGES
caxlsx (3.3.0) lib/axlsx/workbook/worksheet/border_creator.rb:15:in `initialize'
```
- Change `BorderCreator#initialize` arguments handling
- Fix `add_border` to work with singluar cell refs
=> Fix bug in BorderCreator when second arg is nil

.github/workflows/stale.yml
We talked about not closing stale PRs and issues on Slack as this might discourage peaople trying to contribute.
Docs about the changed config: https://github.com/actions/stale#days-before-close
=> Do not close stale PRs and issues automatically [ci skip]

lib/axlsx/package.rb
If argument starts with a pipe character (`'|'`) and the receiver is the `IO` class, a subprocess is created in the same way as `Kernel#open`, and its output is returned. `Kernel#open` may allow unintentional command injection, which is the reason these `IO` methods are a security risk. Consider to use `File.read` to disable the behavior of subprocess invocation.
Close #193
Ref: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Security/IoMethods
=> Use File.read instead of IO.read

README.md, examples/escape_formula_example.md
I think these both are simple typos – can you confirm, @johnnyshields?
=> Fix typos regarding "escape formulas" in readme and example

CHANGELOG.md, lib/axlsx/workbook/worksheet/cell.rb
Follow-up to #190 based on @noniq's comment. Fixes #207, #208.
Suggest to release as 3.4.1.
=> Revert formula characters other than =

.rubocop_todo.yml, lib/axlsx/drawing/vml_drawing.rb, lib/axlsx/drawing/vml_shape.rb
Also use `XML` as delimiter to highlight syntax in supported editors
As usual, please review with whitespaces hidden
This has also been manually tested with
```rb
old_s = <<BAD_PROGRAMMER
<xml xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel">
<o:shapelayout v:ext="edit">
<o:idmap v:ext="edit" data="#{@comments.worksheet.index + 1}"/>
</o:shapelayout>
<v:shapetype id="_x0000_t202" coordsize="21600,21600" o:spt="202"
path="m0,0l0,21600,21600,21600,21600,0xe">
<v:stroke joinstyle="miter"/>
<v:path gradientshapeok="t" o:connecttype="rect"/>
</v:shapetype>
BAD_PROGRAMMER
new_s = <<~XML
<xml xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office" …
```
=> Fix Layout/HeredocIndentation offenses

lib/axlsx/util/validators.rb
I'm following #179  for a while and read the changes in #213 - I agree with most of them, however turning off the validations makes me unconfortable with more complex excel generators, so I tried to reduce the memory consumption there. As @pkmiec pointed out, we're full of unnecessary memory allocations creating lambdas and arrays, so I moved them out to constants.
=> Validation improvements

.rubocop_todo.yml, CHANGELOG.md, lib/axlsx/util/simple_typed_list.rb, test/util/tc_simple_typed_list.rb
This PR is a follow-up to https://github.com/caxlsx/caxlsx/pull/213 and includes the commits related to having SimpleTypedList subclass Array.
The following are some quick numbers on Ruby 3.1.3 on my MacBook. The main point is that performance is bit faster and memory is quite a bit less. I do not fully understand why the previous approach of class_eval and delegating was so much more memory intensive.
Used the benchmark / memory profiler from https://github.com/caxlsx/caxlsx/pull/220/commits/1c355c83a9603f835dfe59ef4473df2b8cc3534c.
```
└─▪ test/benchmark.rb
...
user     system      total        real
axlsx_noautowidth                0.896363   0.007475   0.903838 (  0.904204)
axlsx_autowidth                  0.939241   0.008933   0.948174 (  0.948764)
axlsx_shared …
```
=> SimpleTypedList subclass of Array

.rubocop_todo.yml, CHANGELOG.md, lib/axlsx/util/validators.rb, lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/workbook/worksheet/tc_cell.rb
Treat escape_formulas similar to type, style, formula_value in Axlsx::Cell. This avoid parse_options doing anything and setting `escape_formulas` in the common case  which can be expensive f it happens for each cell.
Also took the opportunity to fix rubocop offenses in cell.rb.    
Here are some quick benchmarks on Ruby 3.1.3 on my macbook. Notice the perf improvements and memory reduction.
```
└─▪ test/benchmark.rb 
...
user     system      total        real
axlsx_noautowidth                0.926718   0.003697   0.930415 (  0.930809)
axlsx_autowidth                  0.895991   0.003213   0.899204 (  0.899484)
axlsx_shared                     0.843739   0.002358   0.846097 (  0.846468)
axlsx_stream                     0.848358   0.002555   0.850913 (  0.850882)
axlsx_zip_command …
```
=> Improve escape formulas

.rubocop_todo.yml, lib/axlsx.rb, lib/axlsx/util/constants.rb, lib/axlsx/workbook/worksheet/cell_serializer.rb, lib/axlsx/workbook/worksheet/row.rb, test/tc_axlsx.rb
The column references are computed in `#col_ref`, but for any 
spreadsheet, the column references in each rows will be the 
same. So we can cache those and avoid small string allocations.
We can also modify `CellSerializer` to directly use `#col_ref` 
and `#row_ref`. 
Overall, we gain a perf improvement and reduction in allocated 
memory. 
The following are on Ruby 3.2.1 on my macbook.
```
└─▪ test/benchmark.rb
...
user     system      total        real
axlsx_noautowidth                0.781451   0.003570   0.785021 (  0.785643)
axlsx_autowidth                  0.777843   0.003068   0.780911 (  0.781048)
axlsx_shared                     0.807382   0.003307   0.810689 (  0.811241)
axlsx_stream                     0.793688   0.003162   0.796850 (  0.797375)
axlsx_zip_command …
```
=> Cache `col_ref` and `row_ref`

.rubocop_todo.yml, lib/axlsx/drawing/pic.rb
Very minor (safe) fix, because I was curious of the difference
```
Warming up --------------------------------------
ivs_string   852.934k i/100ms
ivs_symbol     1.323M i/100ms
Calculating -------------------------------------
ivs_string      8.502M (± 0.2%) i/s -     42.647M in   5.016094s
ivs_symbol     13.287M (± 0.3%) i/s -     67.461M in   5.077418s
Comparison:
ivs_symbol: 13286595.1 i/s
ivs_string:  8502017.1 i/s - 1.56x  (± 0.00) slower
```
=> Fix Performance/StringIdentifierArgument offense

.rubocop_todo.yml, lib/axlsx/workbook/workbook.rb
Fix a couple of performance RuboCop offenses in workbook
```
Warming up --------------------------------------
match_and_select    59.143k i/100ms
include_and_find   123.780k i/100ms
Calculating -------------------------------------
match_and_select    591.904k (± 1.0%) i/s -      3.016M in   5.096401s
include_and_find      1.238M (± 0.8%) i/s -      6.313M in   5.098961s
Comparison:
include_and_find:  1238131.2 i/s
match_and_select:   591904.2 i/s - 2.09x  (± 0.00) slower
Calculating -------------------------------------
match_and_select   947.000  memsize (   499.000  retained)
9.000  objects (     1.000  retained)
3.000  strings (     0.000  retained)
include_and_find   160.000  memsize (     0.000  retained)
4.000  objects (     0.000  retained)
2.000  strings (     0.000  retained) …
```
=> Use `include?` and `find` for performance

lib/axlsx/util/constants.rb, lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/cell_serializer.rb
Ruby 2.5 introduced `delete_prefix` and `delete_suffix`.
Those methods are helpful when serializing formula and array formula values, that are supposed to start and end with given prefixes
Also moves formula prefix to constants so they can be used by both `Cell` and `CellSerializer` classes
Formula:
```
Ruby version: 3.2.2
Comparison:
delete_prefix:  8759353.5 i/s
sub:  2607022.4 i/s - 3.36x  (± 0.00) slower
Comparison:
delete_prefix:         40 allocated
sub:        160 allocated - 4.00x more
```
Array Formula:
```
Ruby version: 3.2.2
Comparison:
delete_prefixes:  4798837.8 i/s
sub_sub:   937072.1 i/s - 5.12x  (± 0.00) slower
Comparison:
delete_prefixes:        120 allocated
sub_sub:        488 allocated - 4.07x more
```
Please describe your pull request. Thank you for contributing! …
=> Replace `sub` with `delete_prefix`/`delete_suffix`

.rubocop_todo.yml, lib/axlsx.rb, lib/axlsx/stylesheet/num_fmt.rb, lib/axlsx/util/serialized_attributes.rb
Serialized attributes are usually declared in snake case as is the convention in Ruby. However, they need to be written in xml in camel case. So the `serialized_attributes` converts each serialied attribute into camel case on each invocation. We can avoid the time / memory for this conversion by caching the conversion the first time and re-using it each subsequent time.
We also avoid using `instance_values_for` to grab all instance variables only to reject ones with nil values and ones that are not serialied attributes. Instead, we can grab only the instance variables that correspond to defined serialied attributes. 
Finally, `Axlsx#booleanize` is commonly used to convert `true` / `false` into `1` / `0` when outputting values to the xml string. However, instead of returning `1` / `0` we …
=> Serialized attributes

CHANGELOG.md, lib/axlsx/workbook/workbook.rb, test/workbook/tc_workbook.rb
I noticed `Workbook#sheet_by_name` sometimes returns `nil` when trying to find a sheet. After investigation, I realized it's because name is encoded [here](https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/workbook/worksheet/worksheet.rb#L328-L331), but not in `sheet_by_name`. This encodes the input in `sheet_by_name`, and also makes a minor refactor to just use `find` instead of `index` and lookup separately.
=> Fix sheet_by_name for sheets with escaped characters

.rubocop_todo.yml, lib/axlsx/workbook/worksheet/cell_serializer.rb, lib/axlsx/workbook/worksheet/rich_text_run.rb
- Style/HashTransformKeys
- Style/HashConversion
```
Comparison (IPS):
transform_keys:  2890030.0 i/s
Hash[map]:  1777641.0 i/s - 1.63x  (± 0.00) slower
Comparison (Memory):
transform_keys:        168 allocated
Hash[map]:        248 allocated - 1.48x more
```
=> Fix hash transformation related offenses

.rubocop_todo.yml, lib/axlsx/workbook/worksheet/data_validation.rb
From Ruby Style Guide:
> Do not use `and` and `or` in boolean context - and and or are control
flow operators and should be used as such. They have very low precedence, and can be used as a short form of specifying flow sequences like "evaluate expression 1, and only if it is not successful (returned `nil`), evaluate expression 2". This is especially useful for raising errors or early return without breaking the reading flow.
Also:
- Remove redundant use of self
- Use attribute reader instead of accessing instance variable
=> Fix Style/AndOr offenses

.github/workflows/test.yml
Also provide a better user message in workflow results when failures are allowed ("allow failures" instead of "true")
=> Test against JRuby head

lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/cell_serializer.rb
In our benchmarks, as I suspect in real world, it is common for cells to use the 
default style of 0. Currently, the CellSerializer asks the cell for its style and
then converts it to a string. We can optimize by adding an "private" method to 
cell to return the style as a string and avoid the conversion of 0 to '0'.
Using Ruby 3.2.1 for the following benchmarks. It appears to be a bit faster, but 
it should be taken with a grain of salt as the perf numbers are not consistent at
these scales.
However, we do avoid allocating 15%! of the memory.
```
└─▪ test/benchmark.rb 
...
user     system      total        real
axlsx_noautowidth                0.545710   0.002926   0.548636 (  0.549055)
axlsx_autowidth                  0.576632   0.002091   0.578723 (  0.579273)
axlsx_shared …
```
=> Add `Cell#style_str` so that we can directly return '0'

.rubocop_todo.yml, lib/axlsx/drawing/axes.rb, lib/axlsx/workbook/worksheet/pane.rb, lib/axlsx/workbook/worksheet/selection.rb, lib/axlsx/workbook/worksheet/sheet_view.rb
Fixes:
- Style/ClassCheck
- Style/ClassEqualityComparison
While `is_a?` and `kind_of?` are equivalent, there is a 5% gain when switching from class comparison to `intance_of?` 
```
Comparison:
instance_of: 16902635.9 i/s
class comparison: 16061288.3 i/s - 1.05x  (± 0.00) slower
```
=> Fix safe class comparison offenses

.rubocop.yml, .rubocop_todo.yml, lib/axlsx/util/mime_type_utils.rb, test/util/tc_mime_type_utils.rb
Also fixes a Security/Open offense that couldn't be exploited, because
the only invocation of `get_mime_type_from_uri` was validating the
input with a `URI::DEFAULT_PARSER` regexp
- [] I have updated the documentation accordingly.
=> Enable Security cops

test/profile.rb
```
NOTE: RubyProf.profile is deprecated; use Profile.profile instead. It will be removed on or after 2023-06.
RubyProf.profile called from ./test/profile.rb:14.
NOTE: RubyProf.running? is deprecated; use Profile#running? instead. It will be removed on or after 2023-06.
NOTE: RubyProf.measure_mode is deprecated; use Profile#measure_mode instead. It will be removed on or after 2023-06.
NOTE: RubyProf.exclude_threads is deprecated; use Profile#exclude_threads instead. It will be removed on or after 2023-06.
```
=> Fix profiler deprecations

lib/axlsx/util/simple_typed_list.rb, test/benchmark.rb
Prior to https://github.com/caxlsx/caxlsx/pull/223, SimpleTypeList was just an object and inheritied #== / #eql? from BasicObject. These versions are fast as they just compare whether two objects sit in the same memory location.
After https://github.com/caxlsx/caxlsx/pull/223, we started to inherit #== / #eql? from Array. These are slow as they crawl all the elements in the Array.
This commit restores the original version of #== / #eql?.
=> Use #== and #eql? from BasicObject

lib/axlsx/workbook/worksheet/cell.rb
Also inverts `string.match(REGEX)` with `REGEX.match(string)` because
of uniformity and because it has been tested 5% more performant on
Ruby 3.2. Performance on older Rubies is the same
```
REGEX.match(string):  1234330.7 i/s
string.match(REGEX):  1172670.1 i/s - 1.05x  (± 0.00) slower
```
=> Improve absolute cell reference method

.rubocop_todo.yml, lib/axlsx/workbook/worksheet/rich_text_run.rb
Replace `keys.each` with hash iteration
```rb
MY_HASH = {
first: '1',
second: '2',
third: '3'
}
%i[ips memory].each do |benchmark|
Benchmark.send(benchmark) do |x|
x.report("each_key") { MY_HASH.each_key { |k| MY_HASH[k] } }
x.report("keys.each") { MY_HASH.keys.each { |k| MY_HASH[k] } }
x.report("each") { MY_HASH.each { |k, v| v } }
x.compare!
end
end
```
```
IPS Comparison:
each:  4283031.6 i/s
each_key:  3683407.4 i/s - 1.16x  (± 0.00) slower
keys.each:  3387425.1 i/s - 1.26x  (± 0.00) slower
Memory Comparison:
each_key:          0 allocated
each:          0 allocated - same
keys.each:         40 allocated - Infx more
```
=> Fix Style/HashEachMethods offense

lib/axlsx/workbook/worksheet/cell.rb
`Cell#initialize` is one of the most used methods in the library, so a small improvement here will make a lot of difference on the overall performance.
The impact of this change is negligible when `options` has elements but is substantial when it is empty.
```
Comparison (empty options):
parse unless: 11636650.6 i/s
parse:  8109825.4 i/s - 1.43x  (± 0.00) slower
Comparison (1 option):
parse:  3548037.5 i/s
parse unless:  3459029.7 i/s - same-ish: difference falls within error
```
=> Avoid unnecessary calls to `parse_options`

.rubocop_todo.yml, lib/axlsx/drawing/chart.rb, lib/axlsx/drawing/drawing.rb, lib/axlsx/drawing/pic.rb, lib/axlsx/drawing/view_3D.rb, lib/axlsx/drawing/vml_drawing.rb, lib/axlsx/stylesheet/styles.rb, lib/axlsx/util/accessors.rb, lib/axlsx/util/validators.rb, lib/axlsx/workbook/workbook.rb, lib/axlsx/workbook/worksheet/comments.rb, lib/axlsx/workbook/worksheet/pivot_table.rb, lib/axlsx/workbook/worksheet/pivot_table_cache_definition.rb, lib/axlsx/workbook/worksheet/table.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/content_type/tc_content_type.rb, test/drawing/tc_vml_drawing.rb, test/workbook/worksheet/tc_comments.rb, test/workbook/worksheet/tc_pivot_table.rb
`Kernel.format` is faster and will avoid to allocate an array compared
to `String#%`.
```
IPS:
kernel_format:  3877614.2 i/s
string_percent:  3531475.0 i/s - 1.10x  (± 0.00) slower
Memory (in case of array parameters):
kernel_format:        160 allocated
string_percent:        200 allocated - 1.25x more
```
=> Fix format string offenses

.rubocop_todo.yml, lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/worksheet_comments.rb, lib/axlsx/workbook/worksheet/worksheet_drawing.rb
Renaming the existing methods would break the public API, and it is not
worth to alias and/or deprecate existing methods, so this commit
enables Naming/PredicateName and allows the existing methods to preserve
their name
=> Enable Naming/PredicateName cop

lib/axlsx/util/constants.rb
All supported Ruby versions now support the `encode` method on strings, so the conditional check for this method has been removed. Even if the default encoding on Ruby >= 2.0 is UTF-8, this is not always the case when the `LANG` environment variable is not set to `C.UTF-8`, so the `encode` method has been preserved.
Additionally, this commit updates a link to use the `https` protocol for improved security.
=> Remove conditional check for `encode` method

.rubocop_todo.yml, lib/axlsx.rb
`Gem.loaded_specs` is a hash, so it is safe to use `key?` and enable this cop
=> Fix Style/PreferredHashMethods offense

lib/axlsx.rb, lib/axlsx/workbook/worksheet/cell.rb
Previously, `require 'cgi'` was only called in `cell.rb`, but there are other components in the Axlsx module that also use this dependency, including `Axlsx::SeriesTitle`, `Axlsx::StrVal`, `Axlsx::Title` (drawing), `Axlsx::Comment`, `Axlsx::ConditionalFormattingRule`, and `Axlsx::HeaderFooter`.
By requiring cgi at the module level, we ensure that this dependency is available to all components in the Axlsx module, which can prevent issues if someone is requiring specific components that depend on cgi.
This change improves the maintainability and reliability of the codebase by ensuring that all components have access to the required dependencies.
Close #282
=> Require 'cgi' at module level

.rubocop_todo.yml, lib/axlsx/util/validators.rb
Uses `Array#any?` instead of `Array#each`.
According to benchmarks, `any?` is slightly faster when validation fails (3%) and noticeably faster when validation passes (up to 60%)
---
I'm consistently getting better results in benchmark after this change, can you please take a look?
=> Fix Lint/NonLocalExitFromIterator offense

lib/axlsx/util/constants.rb
Ref: https://ruby-doc.org/core-2.6.10/Encoding.html#class-Encoding-label-Changing+an+encoding
=> Use encoding constant instead of hardcoded string

lib/axlsx/drawing/area_chart.rb, lib/axlsx/drawing/line_chart.rb
`class.name` is faster, uses less memory than `class.to_s`, and can be used in this context.
This micro optimization does not have practical effect, it is just a reference for the future in case this approach will be needed in other parts of the library
```
Comparison (IPS):
Object.name: 13528803.0 i/s
Object.to_s:  8213612.0 i/s - 1.65x  (± 0.00) slower
Comparison (Memory):
Object.name:          0 allocated
Object.to_s:         40 allocated - Infx more
```
=> Use `class.name` instead of `class.to_s`

CHANGELOG.md, README.md, examples/basic_formula_example.md, examples/cached_formula_example.md, examples/column_outlines_example.md, examples/complex_example.md, examples/defined_name_example.md, examples/row_outlines_example.md, lib/axlsx.rb, test/tc_axlsx.rb, test/workbook/worksheet/tc_cell.rb
It's a rebased version of #189 as I can't push to the original PR, nor change the base branch for the PR.
It sets the global default of `escape_formulas` to true and should be released in 4.0
=> Escape formulas by default

.rubocop_todo.yml, CHANGELOG.md, lib/axlsx/workbook/worksheet/icon_set.rb, test/workbook/worksheet/tc_icon_set.rb
Closes #221 
I turned the code snippet from #221 into a PR.
I renamed the new attribute to `interpolationPoints` as the `Cfvo` class refers to them as interpolation points in the comments (then as `val` in the code).
I also had to move the call for `initialize_value_objects` into the `to_xml_string` method as we can override the interpolation points any time before the actual serialization. I'm not sure if we really need to store it in memory, it could be handy only if we call `to_xml_string` multiple times on the same iconSet.
=> Add optional interpolation points to icon sets

CHANGELOG.md, lib/axlsx/workbook/worksheet/data_validation.rb, test/workbook/worksheet/tc_data_validation.rb
Recently I had to generate an excel sheet where one of the cells got a warning message when the client moves the cursor on it. To do that, I added a `none` type validation to the cell which means there are no bad values, but we'll have the message shown.
However, I've run into a `undefined method `include?' for nil:NilClass` error doing it, so I quickly looked into the source code and found the issue.
With the fix in place, you can run this code snippet to get the expected result
```ruby
sheet.add_data_validation('B1:B10',
type: :none,
showInputMessage: true,
prompt: 'Be extra careful editing this cell!')
```
=> Fix data validations for none type validations to show warnings only

CHANGELOG.md, lib/axlsx/workbook/worksheet/worksheet_hyperlink.rb, test/workbook/worksheet/tc_worksheet_hyperlink.rb
`sheet.add_hyperlink()` converts the given location to "lower camel case", altering sheet names containing underscores in the process, making them invalid.
This PR turns off camelization, as suggested in #311. Closes #311.
- If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- I have updated the documentation accordingly.
=> Don't change hyperlinks 

lib/axlsx/stylesheet/styles.rb, test/stylesheet/tc_styles.rb, test/tc_axlsx.rb, test/workbook/worksheet/tc_data_validation.rb, test/workbook/worksheet/tc_sheet_protection.rb, test/workbook/worksheet/tc_sheet_view.rb
Compared to String#to_sym, symbol conversion is:
- 6 character shorter
- Highlighted as a symbol (at least by TextMate and VS Code)
- 7% faster
This offense is not being detected by Rubocop because caxlsx is using an old version which works on 2.6 and the current version does not detect this problem because of rubocop/rubocop#12373
=> Use symbol conversion instead of to_sym

lib/axlsx/workbook/workbook.rb
Offense found by `fasterer` gem.
Using `attr_reader` for both uniformity and performance (10-20% improvement according to the Ruby version)
Close #318
=> Use attr_reader for use autowidth

test/content_type/tc_content_type.rb, test/doc_props/tc_app.rb, test/doc_props/tc_core.rb, test/drawing/tc_area_chart.rb, test/drawing/tc_bar_3D_chart.rb, test/drawing/tc_bar_chart.rb, test/drawing/tc_bubble_chart.rb, test/drawing/tc_chart.rb, test/drawing/tc_drawing.rb, test/drawing/tc_line_3d_chart.rb, test/drawing/tc_line_chart.rb, test/drawing/tc_pic.rb, test/drawing/tc_pie_3D_chart.rb, test/drawing/tc_pie_chart.rb, test/drawing/tc_scatter_chart.rb, test/drawing/tc_series_title.rb, test/drawing/tc_title.rb, test/rels/tc_relationships.rb, test/stylesheet/tc_styles.rb, test/workbook/tc_shared_strings_table.rb, test/workbook/tc_workbook.rb, test/workbook/worksheet/tc_cell.rb, test/workbook/worksheet/tc_pivot_table.rb, test/workbook/worksheet/tc_pivot_table_cache_definition.rb, test/workbook/worksheet/tc_rich_text_run.rb, test/workbook/worksheet/tc_table.rb, test/workbook/worksheet/tc_worksheet.rb
Replaced size check with empty array check for error messages.
This change simplifies the code by using the default failure message for empty errors, eliminating the need to manually map and display error messages.
=> Refactor error assertions

lib/axlsx/util/accessors.rb
- Fix documentation
- Use a heredoc to define a multi-line string, which makes the code easier to understand at a glance.
- Error Handling: If there's an error in the method definition, it will be easier to debug because the error message will point to the exact line of code where the error occurred.
- Provide a comment block showing the aspect of an interpolated method https://rubystyle.guide/#eval-comment-docs
Old approach:
```
Error: test_add_selection(TestSheetView): RuntimeError: Hello
~/dev/caxlsx/lib/axlsx/util/accessors.rb:59:in `right_to_left='
--> module_eval(format(SETTER, symbol, validator, symbol), __FILE__, __LINE__)
```
New approach:
```
Error: test_to_xml(TestSheetView): RuntimeError: Hello
~/dev/caxlsx/lib/axlsx/util/accessors.rb:58:in `right_to_left='
module_eval …
```
=> Improve validated accessor definition

examples/generate.rb
I meant to generate a few example files using Ruby 3.3.0, but I ran into a LoadError:
```bash
> ./generate.rb
Executing 3d line chart example
<internal:/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- axlsx (LoadError)
from <internal:/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
from (eval at ./generate.rb:13):3:in `block in <main>'
from ./generate.rb:13:in `eval'
from ./generate.rb:13:in `block in <main>'
from ./generate.rb:9:in `each'
from ./generate.rb:9:in `<main>
```
I've looked into what could've caused it, and finally I opened a bug report for Ruby: https://bugs.ruby-lang.org/issues/20175
On the other hand, I realized that we're not populating the `$LOAD_PATH` …
=> Fix example generator script's load path

axlsx.gemspec
These data will appear on rubygems.org
- Bug tracker URL
- Changelog URL
- Source code URL
=> Add metadata to gemspec

lib/axlsx/stylesheet/styles.rb, test/workbook/worksheet/tc_data_validation.rb, test/workbook/worksheet/tc_sheet_view.rb
Starting from Ruby 2.6, it is possible to pass multiple hashes to `Hash#merge`
Ref: https://ruby-doc.org/core-2.6/Hash.html#method-i-merge
Ruby 2.6 on M1 Pro
```
Comparison:
merge(X, Y):  4287524.9 i/s
merge(X).merge(Y):  2785848.9 i/s - 1.54x  (± 0.00) slower
Comparison:
merge(X, Y):        232 allocated
merge(X).merge(Y):        464 allocated - 2.00x more
```
Ref: rubocop/rubocop-performance#447
=> Use a single merge instead of merge chain

CHANGELOG.md, docs/style_reference.md, examples/hide_sheet_example.md, examples/row_heights_example.md
```
codespell **/*.md -w
```
Also strip some trailing whitespaces
=> Fix typos in documentation

README.md
Replaced a link in Readme pointing to a non existent examples file to point to the folder like the others.
=> Fix examples link in Readme [ci skip]

.rubocop.yml, Gemfile
RuboCop::Packaging helps to enforce some of the guidelines that are expected of upstream maintainers so that the downstream can build their packages in a clean environment without any problems.
=> Update RuboCop and add Packaging extension

test/stylesheet/tc_styles.rb
Changed `&&` to `&` in assertion to correctly perform array intersection. `&&` was incorrectly used as a logical AND, so the result of `truthy_value && ['bottom', 'top']` returned `['bottom', 'top']`
```
[] && ['bottom', 'top']
=> ["bottom", "top"] 
```
=> Fix potential false positive assertion

test/workbook/worksheet/auto_filter/tc_auto_filter.rb
The previous test for `AutoFilter#add_column` was passing a block to the method, which was not being used and triggered a warning. This commit modifies the test to directly assert on the return value of `add_column` instead.
This change ensures that the test actually verifies the correct behavior of the `add_column` method, eliminating the potential for false positives and addressing the related warning about ignored blocks.
Close #399
=> Fix warning in `AutoFilter#add_column` test

CHANGELOG.md, lib/axlsx.rb, lib/axlsx/drawing/pic.rb
This commit introduces a new method `Axlsx#uri_parser` to handle URI parsing in a way that's compatible with both newer and older versions of Ruby's URI library. It checks for the presence of `URI::RFC2396_PARSER` and falls back to `URI::DEFAULT_PARSER` if not available, ensuring consistent behavior across different Ruby versions.
Close #397
Ref: ruby/uri#114
=> Add `uri_parser` method for RFC2396 compatibility

lib/axlsx.rb
Requires #398
---
Reorganize dependencies in axlsx.rb 
- Group external and core gem dependencies at the top of the file
- Ensure all dependencies are loaded before internal library files
This change improves the organization and readability of the axlsx.rb
file, making it easier for developers to understand and maintain the
library's dependency structure. The new arrangement provides a clearer
overview of both external and core dependencies required by the axlsx
library.
=> Reorganize dependencies in axlsx.rb

.rubocop_todo.yml, lib/axlsx/util/simple_typed_list.rb, lib/axlsx/workbook/worksheet/worksheet.rb, test/util/tc_simple_typed_list.rb
- Rename `+` method to `concat` for consistency with Array's API
- Avoid confusion caused by `+` unexpectedly modifying the receiver
- Prevent `Lint/Void` offense in static code analysis
Close #294
=> Fix Lint/AmbiguousOperatorPrecedence offense

lib/axlsx.rb
Requires #401
---
Remove unnecessary `bigdecimal` require
The `bigdecimal` require was introduced in commit 11303a4 but appears 
to be unnecessary.
After thoroughly inspecting the codebase, no instances  of `BigDecimal`
or methods like `to_d` and `to_digits` were found, indicating 
that the dependency can safely be removed.
Although `bigdecimal` is indirectly included via the `crack` gem, which
is  a dependency of `webmock`, the only occurrences of `webmock` in the
code  are related to test the method
`Axlsx::MimeTypeUtils.get_mime_type_from_uri` for detecting mime types
of remote files. In this context, `bigdecimal` is not used.
Close #404
=> Do not require bigdecimal

.rubocop.yml, lib/axlsx/content_type/abstract_content_type.rb, lib/axlsx/rels/relationship.rb, lib/axlsx/util/simple_typed_list.rb, lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb, lib/axlsx/workbook/worksheet/cell.rb, lib/axlsx/workbook/worksheet/conditional_formatting.rb, lib/axlsx/workbook/worksheet/data_validation.rb
Switch from using predicate methods like `v.zero?` to direct comparisons
like `v == 0` for performance optimization.
Although this may not yield a visible improvement with the current
implementation, using `== 0` instead of `.zero?` in a method for cell
rendering could lead to significant performance gains in the future.
Benchmarks show that comparisons are faster than predicates across
multiple Ruby versions:
```
Comparison (Ruby 2.6 to 3.2, v = 0):
v == 0: 21479329.3 i/s
v.zero?: 17979885.4 i/s - 1.19x  (± 0.00) slower
Comparison (Ruby 3.3, v = 0):
v == 0: 23652215.7 i/s
v.zero?: 21843174.0 i/s - 1.08x  (± 0.00) slower
Comparison (Ruby 2.6 to 3.3, v = 1):
v == 0: 23227474.2 i/s
v.zero?: 21675200.9 i/s - 1.07x  (± 0.00) slower
```
---
Hello, 
~I'm having slightly and consistently better …
=> Configure Style/NumericPredicate for performance

lib/axlsx/workbook/worksheet/border_creator.rb
This commit updates the `border_creator.rb` file to use a regular expression match instead of `scan`
```rb
def scan
'A1'.scan(/\d+/).first
end
def array_match
'A1'[/\d+/]
end
raise if scan != array_match
%i[ips memory].each do |benchmark|
Benchmark.send(benchmark) do |x|
x.report('scan') { scan }
x.report('array_match') { array_match }
x.compare!
end
end
```
```
IPS Comparison:
array_match:  1770072.4 i/s
scan:   824069.5 i/s - 2.15x  (± 0.00) slower
Memory Comparison:
array_match:        208 allocated
scan:        248 allocated - 1.19x more
```
=> Refactor border_creator for improved performance

lib/axlsx.rb
Slightly simplifies the code and gives a minor performance improvement
on newer Ruby versions
M1 Pro, Ruby 3.3.5 x64, single char:
```
name_to_indices_new:  1370019.0 i/s
name_to_indices:  1322752.7 i/s - 1.04x  (± 0.00) slower
```
M1 Pro, Ruby 3.3.3 ARM, single char:
```
name_to_indices_new:  2324745.0 i/s
name_to_indices:  2157339.6 i/s - 1.08x  (± 0.00) slower
```
=> Use each with object instead of reduce to improve readability and performance

CHANGELOG.md, axlsx.gemspec, lib/axlsx/package.rb, lib/axlsx/util/buffered_zip_output_stream.rb
Since:
- As per Rubyzip's readme, it is not recommended to use any versions of Rubyzip earlier than 2.3 due to security issues
- Rubyzip 2.4 requires Ruby >= 2.4
- Caxlsx requires Ruby >= 2.6
This commit bumps the minimum required Rubyzip version to 2.4 and changes syntax accordingly to allow 3.0 compatibility with the minimum amount of changes to production code
Closes #384
=> Bump Rubyzip requirement to >= 2.4 to allow 3.0

Gemfile, test/drawing/tc_chart.rb, test/drawing/tc_one_cell_anchor.rb, test/stylesheet/tc_styles.rb, test/workbook/worksheet/tc_worksheet.rb
Additionally, autofix safe Style/RedundantParentheses offenses in non-production code
=> Update RuboCop dependency

lib/axlsx/util/simple_typed_list.rb
The new cop flagged a fallback path in `SimpleTypedList#to_xml_string` for cases where `serialize_as` is nil.  
After reviewing the serialization logic and attempting to reproduce a real-world scenario, no case was found where this fallback is invoked in normal usage.  
No consumers, including PivotTables, call `to_xml_string` without a valid `serialize_as` value.  
This code path is therefore not an issue and is currently redundant.
Remove the dead condition for clarity and maintainability.
Close #447
=> Remove redundant `||` fallback in SimpleTypedList

CHANGELOG.md, lib/axlsx/drawing/bar_3D_chart.rb, lib/axlsx/drawing/bar_chart.rb, test/drawing/tc_bar_3D_chart.rb, test/drawing/tc_bar_chart.rb
Problem:
XLSX files for vertical bar charts used `<c:axPos val="b"/>` for the `<c:valAx>` element, which is invalid per the Open XML Spreadsheet specification. The value axis must use `axPos="l"` (left) or `axPos="r"` (right); only `<c:catAx>` should use `axPos="b"` (bottom).
Impact:
Excel opens these files, but Apple Numbers enforces the specification and refuses to open charts with this schema error, causing incompatibility for Numbers users.
Solution:
Update chart XML generation to set `<c:axPos val="l"/>` for `<c:valAx>` and `<c:axPos val="b"/>` for `<c:catAx>`, as specified by the standard.
This is confirmed by extracting the `chart1.xml` from an XLSX file generated by Excel with a standard column/bar chart, where `<c:catAx>` uses `axPos="b"` and `<c:valAx>` uses `axPos="l"`.
For …
=> Fix valAx axis position for Apple Numbers support

examples/active_tab_example.md, lib/axlsx/workbook/workbook_view.rb
- Fix typos in the intro sentence
- Explain that `tab_ratio` sets the sheet tab area vs. scrollbar area (higher value = more tab space).
- Improve documentation for `tab_ratio`
Close #455
=> Improve active_tab_example.md example

CHANGELOG.md, test/doc_props/tc_core.rb
Fixes an annoyance. Timecop is already in the project's Gemfile
=> Use timecop to fix transient time failure in tests
