.travis.yml
appveyor.yml

I added and updated some ruby version to travis and appveyor.

Add latest rubies

---

README.md

Hello, thanks for access. I have set Travis CI for this repo.
I'll try to do the same for rest of repos in this org.

Update README.md to show Travis CI status of this fork.

---

lib/caxlsx.rb

https://guides.rubygems.org/make-your-own-gem/
The convention is to have one Ruby file with the same name as your gem, since that gets loaded when require is run.

Add caxlsx.rb to make auto require work

---

lib/axlsx/package.rb
lib/axlsx/rels/relationship.rb
test/rels/tc_relationship.rb
test/tc_package.rb

Re-open of https://github.com/randym/axlsx/pull/477
Closes #8

Fix Relationship.instances cache

---

CHANGELOG.md
README.md

Lets have one consolidated location for the Changelog

Use CHANGELOG.md instead of README for changelog

---

lib/axlsx/drawing/bar_chart.rb

There's no code changes, only smaller fixes in the comments / docs

Fix typos in BarChart comments

---

README.md

Improve Readme Links to Examples

---

CHANGELOG.md
lib/axlsx/workbook/worksheet/cell.rb
lib/axlsx/workbook/worksheet/rich_text_run.rb
lib/axlsx/workbook/worksheet/worksheet.rb
test/workbook/worksheet/tc_cell.rb
test/workbook/worksheet/tc_rich_text_run.rb

Solves https://github.com/caxlsx/caxlsx/issues/43
Please review.

Improve column auto-width calculations

---

lib/axlsx/workbook/worksheet/pivot_table.rb
test/workbook/worksheet/tc_pivot_table.rb

Support number format in pivot tables.

Add support for format in pivot tables

---

lib/axlsx.rb

This PR contains the safe small part of https://github.com/caxlsx/caxlsx/pull/82 optimization as mentioned in https://github.com/caxlsx/caxlsx/pull/82#issuecomment-803440051

feature: cell_range method optimization

---

CHANGELOG.md

Hi guys,
I have found incorrect markdown in the CHANGELOG.md file. For example: `** February.2.12**`. I changed to  `**February.2.12**`. Thank you.

Improvement: Update CHANGELOG.md

---

examples/borders_example.md

I had to run the examples when I tried to figure out an issue and found that one of our examples is failing

Fix borders example

---

.github/pull_request_template.md
CHANGELOG.md

We discussed that on Slack that it would be great to add a PR template. I also went through the changelog and added some missing entries to make upgrades easier..

Add pull request template and missing changelog entries [ci skip]

---

CHANGELOG.md
examples/list_validation_example.md
lib/axlsx/workbook/worksheet/data_validation.rb
test/support/capture_warnings.rb
test/tc_package.rb
test/workbook/worksheet/tc_data_validation.rb

See the discussion on the related issue. Close #154

Add hideDropDown alias for showDropDown method as it has an inverted logic

---

lib/axlsx/util/constants.rb
lib/axlsx/workbook/worksheet/worksheet.rb

Close #163
Hello, my first contribution here
Please review for:
- constant name
- constant position
- documentation comment change

Add worksheet name max length to a constant

---

CHANGELOG.md
README.md
lib/axlsx/version.rb

Version bump to 3.3.0 [skip ci]

---

README.md

Update http links to https
[ci skip]

[ci skip] Switch to https where possible

---

.github/workflows/stale.yml

Fixing github-actions bot to not close stale issues / PRs immediately. 
https://github.com/actions/stale/issues/44#issuecomment-614827612

Use stale@v2 to fix autoclosing issues

---

CHANGELOG.md
lib/axlsx/workbook/worksheet/sheet_pr.rb

Fix tab color assignment

---

.github/workflows/test.yml

- Test against Ruby 3.2 and JRuby 9.4
- Update a deprecated GitHub action

Improve CI workflow

---

CHANGELOG.md
Gemfile
lib/axlsx.rb
lib/axlsx/util/mime_type_utils.rb
lib/axlsx/version.rb
lib/axlsx/workbook/worksheet/worksheet.rb
test/drawing/tc_pic.rb
test/tc_helper.rb
test/util/tc_mime_type_utils.rb

Addressing a few issues after merging ready PRs and bumping the version to the next minor.
Close #201
Close #200

Release candidate 3.4.0

---

README.md

Use the new code generated by GitHub actions
[ci skip]

Add RuboCop badge and fix Test badge

---

.github/workflows/test.yml

Test against Ruby head

---

.rubocop.yml
.rubocop_todo.yml
lib/axlsx/drawing/axis.rb
lib/axlsx/drawing/chart.rb
lib/axlsx/drawing/view_3D.rb
lib/axlsx/package.rb
lib/axlsx/stylesheet/styles.rb
lib/axlsx/util/simple_typed_list.rb
lib/axlsx/workbook/worksheet/auto_filter/filters.rb
lib/axlsx/workbook/worksheet/cell.rb
lib/axlsx/workbook/worksheet/rich_text_run.rb
lib/axlsx/workbook/worksheet/sheet_protection.rb
lib/axlsx/workbook/worksheet/worksheet.rb

- Lint/RedundantStringCoercion
- Style/CommentAnnotation offenses
- Style/DefWithParentheses
- Style/EvalWithLocation
- Style/MethodCallWithoutArgsParentheses
- Style/MethodDefParentheses
- Style/NilComparison
- Style/Semicolon

Fix safe, minor offenses to production code

---

.rubocop.yml
.rubocop_todo.yml
Gemfile
test/stylesheet/tc_styles.rb
test/support/capture_warnings.rb
test/tc_package.rb
test/workbook/tc_shared_strings_table.rb

Also fixes performance offences in non-production code

Introduce RuboCop performance

---

README.md

Fix minimum supported Ruby version in Readme

---

.rubocop_todo.yml

Regenerate RuboCop Todo

---

README.md
lib/axlsx.rb
lib/axlsx/drawing/d_lbls.rb
lib/axlsx/drawing/hyperlink.rb
lib/axlsx/drawing/vml_drawing.rb
lib/axlsx/package.rb
lib/axlsx/rels/relationship.rb
lib/axlsx/stylesheet/cell_style.rb
lib/axlsx/stylesheet/num_fmt.rb
lib/axlsx/stylesheet/styles.rb
lib/axlsx/util/constants.rb
lib/axlsx/workbook/workbook.rb
lib/axlsx/workbook/worksheet/cell.rb
lib/axlsx/workbook/worksheet/date_time_converter.rb
lib/axlsx/workbook/worksheet/row_breaks.rb
lib/axlsx/workbook/worksheet/worksheet.rb

- `should_use_same_id_as?` has been replaced by `ids_cache_key` in 913003e
[ci skip]
```
[warn]: @param tag has unknown parameter name: Hash 
in file `lib/axlsx.rb' near line 197
[warn]: @param tag has unknown parameter name: Hash 
in file `lib/axlsx.rb' near line 197
[warn]: @param tag has unknown parameter name: styles 
in file `lib/axlsx/workbook/worksheet/cell.rb' near line 88
[warn]: @param tag has unknown parameter name: cell 
in file `lib/axlsx/workbook/worksheet/worksheet.rb' near line 586
[warn]: @param tag has unknown parameter name: cell 
in file `lib/axlsx/workbook/worksheet/worksheet.rb' near line 607
[warn]: @param tag has unknown parameter name: border 
in file `lib/axlsx/workbook/worksheet/worksheet.rb' near line 607
[warn]: In file `lib/axlsx/rels/relationship.rb':46: …
```

Fix YARD warnings

---

.rubocop_todo.yml
lib/axlsx/package.rb
lib/axlsx/workbook/workbook.rb
lib/axlsx/workbook/worksheet/sheet_pr.rb

Fix Style/ZeroLengthPredicate unsafe offenses

---

lib/axlsx/workbook/worksheet/header_footer.rb
lib/axlsx/workbook/worksheet/sheet_protection.rb

Fix Lint/UselessAssignment offenses

---

.rubocop_todo.yml
lib/axlsx/drawing/d_lbls.rb
lib/axlsx/workbook/worksheet/col.rb
lib/axlsx/workbook/worksheet/page_setup.rb

There were 8 occurrences of `!nil?` and 4 of `!= nil`. This change will standardize the usage of non-nil checks

Fix Style/NonNilCheck offenses

---

.rubocop_todo.yml
lib/axlsx/package.rb

Fix Style/LineEndConcatenation offenses

---

.rubocop_todo.yml
lib/axlsx/workbook/worksheet/merged_cells.rb

Axlsx::Row is now an Array, so it is possible to remove the extra
duplicate branch

Remove duplicate branch condition

---

.rubocop.yml
.rubocop_todo.yml
axlsx.gemspec
lib/axlsx/util/simple_typed_list.rb

Also fix safe minor offenses
- Naming/BinaryOperatorParameterName
- Naming/HeredocDelimiterCase

Enable Naming cops

---

.rubocop_todo.yml
lib/axlsx/stylesheet/styles.rb

Please review with "hide whitespaces"

Fix Style/IfInsideElse offense

---

.rubocop_todo.yml
lib/axlsx/drawing/area_series.rb
lib/axlsx/drawing/line_series.rb
lib/axlsx/drawing/pie_series.rb
lib/axlsx/drawing/scatter_series.rb
lib/axlsx/stylesheet/color.rb
lib/axlsx/util/constants.rb
lib/axlsx/workbook/worksheet/dimension.rb
lib/axlsx/workbook/worksheet/worksheet.rb

Fix string concatenation in production code

---

.rubocop_todo.yml
lib/axlsx/workbook/worksheet/col.rb

Fix Style/YodaCondition offense

---

.rubocop_todo.yml
lib/axlsx/drawing/cat_axis.rb
lib/axlsx/drawing/line_3D_chart.rb
lib/axlsx/drawing/pic.rb
lib/axlsx/drawing/view_3D.rb
lib/axlsx/stylesheet/dxf.rb
lib/axlsx/util/storage.rb
lib/axlsx/workbook/worksheet/auto_filter/filter_column.rb
lib/axlsx/workbook/worksheet/auto_filter/filters.rb
lib/axlsx/workbook/worksheet/data_bar.rb
lib/axlsx/workbook/worksheet/sheet_view.rb

Fix Style/MutableConstant offenses

---

.rubocop_todo.yml
lib/axlsx/drawing/area_series.rb
lib/axlsx/drawing/bar_3D_chart.rb
lib/axlsx/drawing/bar_chart.rb
lib/axlsx/drawing/line_3D_chart.rb
lib/axlsx/drawing/line_series.rb
lib/axlsx/drawing/scatter_series.rb
lib/axlsx/package.rb
lib/axlsx/stylesheet/font.rb
lib/axlsx/util/validators.rb
lib/axlsx/workbook/worksheet/pivot_table.rb
lib/axlsx/workbook/worksheet/rich_text_run.rb
lib/axlsx/workbook/worksheet/worksheet.rb

- Style/ParenthesesAroundCondition
- Style/RedundantParentheses
- Style/TernaryParentheses
`Style/ParenthesesAroundCondition` may be questionable, but a majority
of comparison where not using parentheses, so offenses have been fixed
for uniformity across the codebase

Remove redundant parentheses

---

.rubocop_todo.yml
lib/axlsx/drawing/vml_shape.rb

- Style/OperatorMethodCall
- Style/RandomWithOffset
The suggested implementation also uses Array.new to avoid an extra
allocation
```
Comparison (IPS):
Array.new(8) { rand(65..89).chr }.join:   492433.7 i/s
(0...8).map { 65.+(rand(25)).chr }.join:   432155.8 i/s - 1.14x  (± 0.00) slower
Comparison (Memory):
Array.new(8) { rand(65..89).chr }.join:        440 allocated
(0...8).map { 65.+(rand(25)).chr }.join:        560 allocated - 1.27x more
```

Refactor random char generation

---

lib/axlsx/workbook/worksheet/cell.rb
lib/axlsx/workbook/worksheet/cell_serializer.rb
lib/axlsx/workbook/worksheet/rich_text_run.rb

Check for `nil` before checking for more expensive conditions which include a method call or an array scan.
Also removes redundant comments on self-explanatory code

Invert nil checks to improve performance

---

.rubocop_todo.yml
lib/axlsx/workbook/worksheet/sheet_protection.rb
test/workbook/worksheet/tc_sheet_protection.rb

- Lint/AmbiguousOperatorPrecedence
- Style/PerlBackrefs
- Style/StringChars
- Style/UnpackFirst

Fix offenses in sheet protection

---

.rubocop_todo.yml
lib/axlsx/workbook/worksheet/worksheet_drawing.rb

Provide documentation to two attribute readers which triggered the offense.

Fix Style/AccessorGrouping offense

---

.github/workflows/yard.yml
lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
lib/axlsx/workbook/worksheet/auto_filter/sort_condition.rb
lib/axlsx/workbook/worksheet/auto_filter/sort_state.rb

Fix yard documentation warnings

---

examples/README.md

Link chart series colors example properly

---

.rubocop_todo.yml
axlsx.gemspec

Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/

Opt-in for MFA requirement

---

.rubocop_todo.yml
lib/axlsx/drawing/axes.rb
lib/axlsx/workbook/worksheet/pivot_table.rb
lib/axlsx/workbook/worksheet/sheet_view.rb

Fix Lint/UnusedBlockArgument offenses

---

.rubocop_todo.yml
axlsx.gemspec

- Style/ExpandPathArguments
- Style/PercentLiteralDelimiters

Fix minor safe offenses to gemspec

---

CHANGELOG.md
lib/axlsx/version.rb

It looks like we're ready for a 4.0 release :tada: . We have a few breaking changes and a lot of performance and code style improvements! See the changelog for details

Version bump to 4.0.0

---

.rubocop_todo.yml

Update RuboCop ToDo config

---

.github/dependabot.yml
.github/workflows/rubocop.yml
.github/workflows/stale.yml
.github/workflows/test.yml
.github/workflows/yard.yml

Dependabot will search for new actions daily and open a PR if they are available

Update actions and configure Dependabot

---

.github/workflows/test.yml

We got some performance regression (hopefully it'll be fixed in the next point release), but it looks like we don't need anything else to support 3.3.0
- I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- I have updated the documentation accordingly.
- I added an entry to the [changelog](../blob/master/CHANGELOG.md).

Add Ruby 3.3 to the CI matrix

---

test/benchmark.rb
test/profile.rb
test/profile_memory.rb

Do not shuffle the array to always have the same input

Make benchmarks reproducible

---

CHANGELOG.md
lib/axlsx/workbook/worksheet/auto_filter/filter_column.rb
test/workbook/worksheet/auto_filter/tc_filter_column.rb

Closes #328 . Not just the reader was wrong, but the writer method too.
- If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- I have updated the documentation accordingly.

Fix show button for filter columns

---

CHANGELOG.md
lib/axlsx/version.rb

We have some changes on master since the last release and there's already a ticket asking for one of the new features (see #352), so it might be a good time to make a new release.
Currently there are 4 open PRs. Two of them (#315 and #323) are marked as draft, #350 requires some changes and #351 might not be necessary as we already have a solution for the problem it tries to solve. For me it looks like we are at a stable point and we could make the release. What do you think?

Version bump to 4.1.0

---

lib/axlsx/package.rb

Fix typo in comment in package.rb [ci skip]

---

lib/axlsx/stylesheet/styles.rb

Partially reverts 55a0dd9
Ref: #371

Remove Ruby 1.8.7 leftover

---

lib/axlsx/stylesheet/styles.rb

[ci skip] Fix fg_color values in docs examples

---

lib/axlsx/util/serialized_attributes.rb

Removes comment, see #371 
- I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- I have updated the documentation accordingly.
- I added an entry to the [changelog](../blob/master/CHANGELOG.md).

Remove reference to old ruby version from the comments

---

lib/axlsx/drawing/pic.rb

Remove extra whitespace

---

CHANGELOG.md

Added a few changes that may deserve an entry in the changelog
skipping CI because there are no changes to production code

Add some missing entries to the changelog

---

CHANGELOG.md
lib/axlsx/version.rb

As mentioned in #416 , it's been a while since the last release. Here we go, v4.2.0

Version bump to 4.2.0

---

.github/workflows/rubocop.yml
.github/workflows/test.yml
.github/workflows/yard.yml

Test against Ruby 3.4

---

.rubocop.yml
Gemfile
lib/axlsx/workbook/worksheet/header_footer.rb

Additionally:
- Autofix safe `Layout/TrailingWhitespace` offence
- Disable `Style/MultipleComparison` for performance on Ruby < 3.4
`Array#include?` is faster and uses the same amount of memory than multiple comparison only on Ruby >= 3.4, but it is significantly slower on older versions of Ruby, so the cop has been disabled.
```rb
def plain_string_compare?(type)
(type == :string || type == :text)
end
def plain_string_include?(type)
[:string, :text].include?(type)
end
```
```
Comparison (IPS):
multiple_compare: 17158982.8 i/s
include: 12344698.1 i/s - 1.39x  (± 0.00) slower
Comparison (Memory):
multiple_compare:          0 allocated
include:         40 allocated - Infx more
Comparison (IPS):
multiple_compare: 12142357.8 i/s
include:  8668233.0 i/s - 1.40x  (± 0.00) slower
Comparison …
```

Update RuboCop to 1.70.0

---

README.md

Add instructions on how to run local YARD server

---

CHANGELOG.md
lib/axlsx/version.rb

Version bump to 4.3.0
